services:
  - type: web
    name: hikima
    env: docker
    region: frankfurt
    repo: https://github.com/Maidanda144/AttendanceBackend
    buildCommand: "dotnet publish -c Release"
    startCommand: "dotnet bin/Release/net9.0/AttendanceBackend.dll"
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
